# Generated by Django 4.1.1 on 2022-09-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='joke/photo/%Y%m%d%H%M%S/', verbose_name='本站托管图片')),
                ('foreign_url', models.URLField(blank=True, verbose_name='外部图片链接')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='标题')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='正文')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='标题')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文本',
                'verbose_name_plural': '文本',
                'ordering': ('-created',),
            },
        ),
    ]
