# Generated by Django 4.0.4 on 2022-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photo/%Y%m%d%H/', verbose_name='本站托管图片')),
                ('foreignUrl', models.URLField(blank=True, unique=True, verbose_name='外部图片链接')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ('-created',),
            },
        ),
    ]
