# Generated by Django 4.1 on 2022-08-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='摘要')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
    ]
