# Generated by Django 4.1 on 2022-08-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0002_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ('-created',), 'verbose_name': '文本', 'verbose_name_plural': '文本'},
        ),
    ]
