# Generated by Django 4.1 on 2022-08-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0003_alter_text_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='joke/photo/%Y%m%d%H%M%S/', verbose_name='本站托管图片'),
        ),
        migrations.AlterField(
            model_name='text',
            name='description',
            field=models.CharField(blank=True, max_length=120, verbose_name='描述'),
        ),
    ]
