# Generated by Django 3.2.12 on 2022-02-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date', '-question_text'], 'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
    ]
