# Generated by Django 4.1.5 on 2023-01-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, default='book/default.pdf', null=True, upload_to='book/%Y%m%d%H%M%S/', verbose_name='文件'),
        ),
    ]
