# Generated by Django 4.1.3 on 2022-11-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='link',
            field=models.CharField(max_length=1024, unique=True, verbose_name='配置链接'),
        ),
    ]
