# Generated by Django 4.2.1 on 2023-06-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('link', models.TextField(verbose_name='订阅链接')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订阅',
                'verbose_name_plural': '订阅',
                'ordering': ['-updated'],
            },
        ),
    ]
