# Generated by Django 4.2.1 on 2023-06-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='令牌'),
        ),
    ]
