# Generated by Django 4.2.1 on 2023-06-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_alter_account_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-updated'], 'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
    ]
