# Generated by Django 4.1.7 on 2023-05-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morningstar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiableSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('lover', 'lover')], max_length=255, unique=True)),
                ('value', models.BooleanField()),
            ],
        ),
    ]
