# Generated by Django 3.2.9 on 2022-02-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morningstar', '0002_auto_20220207_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '档案', 'verbose_name_plural': '档案'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
