# Generated by Django 4.1.7 on 2023-05-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morningstar', '0002_visiablesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visiablesetting',
            options={'verbose_name': '显示', 'verbose_name_plural': '显示'},
        ),
        migrations.AlterField(
            model_name='visiablesetting',
            name='value',
            field=models.BooleanField(default=True),
        ),
    ]
