# Generated by Django 4.2.6 on 2023-10-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morningstar', '0003_alter_visiablesetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='昵称'),
        ),
    ]
