# Generated by Django 3.2.9 on 2022-02-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Morningstar', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
