# Generated by Django 3.2.12 on 2022-02-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morningstar', '0006_auto_20220207_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='昵称'),
        ),
    ]
