# Generated by Django 4.0.4 on 2022-05-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morningstar', '0007_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.svg', null=True, upload_to='avatar/%Y%m%d%H%M%S/', verbose_name='头像'),
        ),
    ]
