# Generated by Django 4.1 on 2022-08-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readtime',
            field=models.IntegerField(null=True, verbose_name='阅读时间'),
        ),
    ]
