# Generated by Django 4.2 on 2023-05-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_requirelogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='readtime',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='阅读时间'),
        ),
    ]
