# Generated by Django 4.1.7 on 2023-03-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='isLocked',
            field=models.BooleanField(default=False),
        ),
    ]
